server:
  port: 1991
spring:
  cloud:
    config:
      server:
        git:
          timeout: 60000
          clone-on-start: true
          search-paths: cloud-config/config-refresh
          default-label: master
          uri: https://github.com/l362231323/spring-cloud.git

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
    metadata-map:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone:  http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:1990/eureka/

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}