# Web容器配置
server:
  port: 1990

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/
  server:
    enable-self-preservation: false
security:
   user:
      name: user
      password: ${REGISTRY_SERVER_PASSWORD:password}